### ISSUE TITLE
sharp error 

### ISSUE THREAD

**Issue by djixadin** [nuxt/image#1046]
```
{
"error": {
"message": "[500] [IPX_ERROR] \nSomething went wrong installing the \"sharp\" module\n\nModule did not self-register: '/node_modules/sharp/build/Release/sharp-linux-x64.node'.\n\nPossible solutions:\n- Using worker threads? See https://sharp.pixelplumbing.com/install#worker-threads\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install"
}
}
```
 i seem to get this error when using default ipx provider and when fetching images from external url... some images load some do not.
 
 ```
   image: {
    domains: ['https://cd3.example.com'],
    alias: { cdn3: 'https://cd3.example.com' }
  },
 ```

**Comment by djixadin** [comment]
and alias isnt really working

**Comment by danielroe** [comment]
Have you followed the instructions in the error message?

**Comment by djixadin** [comment]
yes and it didnt help. i also tried switching to yarn to see if it helps and it didnt. im using rc3

**Comment by danielroe** [comment]
It's likely an issue with your system rather than Nuxt Image. Perhaps you can provide more information?

**Comment by djixadin** [comment]
its not just me everyone in the team, has this problem. im on ubuntu, the rest is on macos and the server is fedora and its problem everywhere. on every machine node v18.18 is used

**Comment by djixadin** [comment]
seems i have fixed it by adding sharp to build.transpile array

**Comment by djixadin** [comment]
it has indeed helped with images coming from external domain

**Comment by naseefpv** [comment]
> seems i have fixed it by adding sharp to build.transpile array.. will still have to test it thoroughly

Could you please explain how to do that? Thank you

**Comment by djixadin** [comment]
```  build: {
    transpile: ['sharp']
  },
  ```

you need this in nuxt.config.ts but this seems to help only temporary to me. maybe sharp just destroys itself after sometime. not really sure anymore about this package

**Comment by djixadin** [comment]
this seems to be fixed after the latest ipx release but only for images from external domain.. images from public folder are still sometimes not loaded in production

**Comment by djixadin** [comment]
seems now those are fixed as well.. guess it was sharp caching problem all along. guess you can close this

**Comment by naseefpv** [comment]
> seems now those are fixed as well.. guess it was ipx caching problem all along. guess you can close this
I still get the issue randomly, I use latest Nuxt, Nuxt-Image, IPX all.

could you please help to me to clear the ipx caching you mentioned.?

**Comment by songjianet** [comment]
I hope to reopen this question. I am using node20x. After the build, the local png image part will have this problem, but the local svg and remote jpg will have no problem.

**Comment by Fernando12mais** [comment]
What fixed it for me was yarn add sharp --ignore-engines

**Comment by NyllRE** [comment]
this issue still persists. What @djixadin said with it "destroying itself after sometime" is accurate, it seriously does this for some reason. I'm using bun on Debian WSL in windows 11.

**Comment by Droces** [comment]
I've discovered a few ways to tackle this, but they require a bit of explanation.
The basic problem is that we're installing the packages on a different architecture to the prod / deployment architecture, and the Sharp packages (that Next Image relies on) is architecture-specific.

In my case for example, my development machine (where I install packages and where I run the build process) is Mac OS (M1 using ARM), but my deployment environment is Debian linux (using x86).

So to solve this, we have essentially 3 options:

1. Run install and build in an environment with the same architecture as prod
2. Force our package manager to install the version of Sharp for our prod environment **_in_** our development environment
3. Only use Nuxt Image (with IPX) on static pages that are pre-rendered

If you want to do option 1 (probably the best long-term), you could do the install and build:

- On a different machine that has the right environment
- On your machine within a virtual machine or Docker image (however it might not work within a docker image)
- Within a cloud CI / CD process, e.g. using Github Actions or GitLab CI/CD

I really wanted to do option 2 (to build in my dev environment, for convience), but I couldn't get it to work.

For option 3 (only using it on static pages, so the image processing happens during build in your dev environment), you can either build the entire site using `nuxt build`, or build individual pages using `prerender: true` within `routeRules` in the nuxt.config file.
