### ISSUE TITLE
Compatibility Issue with @nuxt/image on Apple M4 Chip (macOS 15.3.1)

### ISSUE THREAD

**Issue by luzehe** [nuxt/image#1702]
**Description**:

I am encountering an issue when using the `@nuxt/image` module on a device with an **Apple M4 chip** running **macOS 15.3.1**. The error occurs during runtime, indicating that the `sharp` module cannot be found. This issue does not occur on other platforms (e.g., Windows), suggesting a compatibility issue specific to the Apple M4 architecture. Here is the relevant code:

```vue
<template>
  <div>
    <NuxtImg src="/images/logo-w.png"></NuxtImg>
  </div>
</template>
```

### Error Message
When running the Nuxt.js project with `@nuxt/image`, I receive the following error:

```plaintext
[500] [IPX_ERROR] 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- /path/to/project/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/sharp.js
- /path/to/project/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/constructor.js
- /path/to/project/node_modules/.pnpm/sharp@0.32.6/node_modules/sharp/lib/index.js
```

### Environment
- **Chip**: Apple M4
- **Operating System**: macOS 15.3.1 (24D70)
- **Node.js Version**: v22.14.0
- **Package Manager**: pnpm@10.4.0
- **Nuxt.js Version**: 3.15.4
- **@nuxt/image Version**: 1.9.0
- **sharp Version**: 0.32.6

### Project Configuration
Here is the relevant part of my `package.json`:

```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@nuxt/image": "1.9.0",
    "nuxt": "^3.15.4",
    "vue": "latest",
    "vue-router": "latest"
  },
  "packageManager": "pnpm@10.4.0+sha512.6b849d0787d97f8f4e1f03a9b8ff8f038e79e153d6f11ae539ae7c435ff9e796df6a862c991502695c7f9e8fac8aeafc1ac5a8dab47e36148d183832d886dd52"
}
```

### Steps to Reproduce
1. Set up a Nuxt.js project on a device with an Apple M4 chip running macOS 15.3.1.
2. Add and configure the `@nuxt/image` module.
3. Run the project using `pnpm dev` or `npm run dev`.
4. The error occurs when `@nuxt/image` tries to use the `sharp` module.

### Possible Solutions Tried
- Reinstalled `sharp` with platform-specific flags:  
  ```bash
  npm install --platform=darwin --arch=arm64 sharp
  ```
- Verified that `sharp` is installed correctly by running:  
  ```bash
  npx sharp --version
  ```
- Checked the `@nuxt/image` documentation for any platform-specific configurations.

### Additional Context
- The issue seems to be specific to the combination of `@nuxt/image` and the Apple M4 chip.
- The `sharp` module itself installs correctly, but `@nuxt/image` fails to use it properly on macOS ARM64 (Apple M4).

### Request
Could you please investigate this compatibility issue? Is there a known workaround or fix for using `@nuxt/image` on devices with Apple M4 chips?

Thank you for your help!

---

**Comment by alexfriesen** [comment]
I had an similar problem. try to install `"ipx": "^3.0.1"`

**Comment by Vahagn-Zaqaryan** [comment]
I'm having the same issue on Apple M2 I just switched my project from `npm` to `pnpm` and the problem occurred.

Weirdly the fix suggested by @alexfriesen worked!

**Comment by alexfriesen** [comment]
I'm glad it worked.
The current version of `@nuxt/image` uses ipx version 2.x.x, which depends on sharp version 0.32.x.
If you upgrade ipx to version 3.x.x, sharp version 0.33.x is used. 
sharp version 0.33.x had some big changes and seems to work better with macs

**Comment by heyflo** [comment]
Wow thank you @alexfriesen 🙏 
I was scratching my head for 2 hours trying even the simplest version and I've found this issue.

This has to be indicated somewhere in the doc with a warning or even better if you could upgrade the dependency on ipx?

**Comment by alexfriesen** [comment]
The previous workaround won't work with the latest nuxt release.
Add this to your `package.json`:
```json
  "resolutions": {
    "ipx": "^3.0.0"
  }
```

**Comment by lucpotage** [comment]
Thank you very much @alexfriesen!

**Comment by 0PandaDEV** [comment]
I have the exact same issue. I did all the steps to fix it and now I get this `detectLibc.isNonGlibcLinuxSync is not a function`

**Comment by zbf1999** [comment]
Thank you very much @alexfriesen!

**Comment by DanceWithBikes** [comment]
thank you @alexfriesen , saved tons of nervous

**Comment by luc122c** [comment]
This should be fixed now [v2 is released](https://github.com/nuxt/image/releases/tag/v2.0.0)

**Comment by jd-solanki** [comment]
I'm very sorry for commenting on the closed issue, but these issues still persist

```
dependencies:
nuxt 4.2.1
@nuxt/image 1.11.0
└─┬ ipx 2.1.1
  └── sharp 0.32.6
```

Can we reopen this for verification?

cc: @danielroe @luc122c

**Comment by danielroe** [comment]
Nuxt Image v2 has been released with a new major version of IPX.

it looks like you are still using Nuxt Image v1.
