### ISSUE TITLE
Requesting SVGs via <NuxtImg /> results in 500 since 2.0.0

### ISSUE THREAD

**Issue by Kuuzoo** [nuxt/image#2035]
When trying to request any SVG using <NuxtImg /> tag I do get a error 500 containing the following error message. This was not an issue before using version 2.0.0. I'm using `bun 1.3.2` as a package manager.

`[500] [IPX_ERROR] Cannot find module 'projectroot/server/node_modules/svgo/node_modules/css-tree/lib/index.js' imported from projectroot/server/node_modules/svgo/plugins/cleanupEnableBackground.js\nDid you mean to import \"css-tree/cjs/index.cjs\"?`

Also out of curiosity how would we best install the sharp binaries for our production server? I'm building on a `darwin arm64` system but want to build for target `linux x64`? I can install the packages using `bun install --cpu=x64 --os=linux` but it will still log the following after building `ℹ sharp binaries have been included in your build for darwin-arm64. Make sure you deploy to the same architecture.                                         @nuxt/image 10:02:48 AM`

**Comment by miguel-arrf** [comment]
We have the same issue for SVGs.

**Comment by n-rowe** [comment]
This is because of an upstream issue in `css-tree`.

I was able to workaround the issue by overriding the css-tree version in my project so that it's the same.
I had css-tree 3.x and 2.x as peer dependencies in the same project and making them all 2.x seemed to work.
I checked with `pnpm why css-tree`

see: https://github.com/nuxt/image/issues/1967#issuecomment-3521988668

**Comment by Kuuzoo** [comment]
> This is because of an upstream issue in `css-tree`.
> 
> I was able to workaround the issue by overriding the css-tree version in my project so that it's the same. I had css-tree 3.x and 2.x as peer dependencies in the same project and making them all 2.x seemed to work. I checked with `pnpm why css-tree`
> 
> see: [#1967 (comment)](https://github.com/nuxt/image/issues/1967#issuecomment-3521988668)

I see, thank you for the insight.
Still I think it would be great to get this resolved in the regarding packages.

https://github.com/svg/svgo/issues/2149#issuecomment-3632467489

If you say it works on 2.x and svgo does directly require 3.x (based on the linked comment above), maybe @SethFalco's thought of replacing the whole `css-tree` dependency inside of `svgo` would now be a good thing to do.

**Comment by develth** [comment]
This fixed it for me (yarn):

**package.json:**
```
"resolutions": {
  "css-tree": "2.2.1"
}
```

**nuxt.config.ts:**
```
nitro: {
    externals: {
      traceInclude: [
        'node_modules/css-tree/data/patch.json',
      ]
    }
},
```

**Comment by Willen17** [comment]
I am using npm and doing the equivalent thing that @develth and @n-rowe suggested did not remove the error.

**package.json:**

```
 "overrides": {
    "sharp": "0.34.4",
    "css-tree": "2.2.1"
  },
```

**nuxt.config.ts:**

```
  nitro: {
    externals: {
      traceInclude: [
        // https://github.com/nuxt/image/issues/2035
        'node_modules/css-tree/data/patch.json'
      ]
    }
  }
```

**Comment by develth** [comment]
@Willen17  did you removed .nuxt and node_modules before testing?

**Comment by Willen17** [comment]
@develth Yup. Still getting errors such as this for SVGs:

```
{
    "error": {
        "message": "[500] [IPX_ERROR] Cannot find module '../data/patch.json'\nRequire stack:\n- /home/nuxt/.output/server/node_modules/css-tree/lib/data-patch.js"
    }
}
```

**Comment by 0x4c756e61** [comment]
> [@develth](https://github.com/develth) Yup. Still getting errors such as this for SVGs:
> 
> ```
> {
>     "error": {
>         "message": "[500] [IPX_ERROR] Cannot find module '../data/patch.json'\nRequire stack:\n- /home/nuxt/.output/server/node_modules/css-tree/lib/data-patch.js"
>     }
> }
> ```

Having the same issue here, with SVGs as well

**Comment by develth** [comment]
whats in that folder?
/home/nuxt/.output/server/node_modules/css-tree/

**Comment by 0x4c756e61** [comment]
> whats in that folder? /home/nuxt/.output/server/node_modules/css-tree/

```
$ ls .output/server/node_modules/css-tree/
lib/ 
package.json
```

**Comment by hybes** [comment]
I submitted PR on https://github.com/svg/svgo/issues/2149 - which wraps the csstree and csso, you can wait for it be merged, or can use it by overriding your svgo deps with my fork:

```package.json
"dependencies": {
	"svgo": "github:Hybes/svgo#fix/bundler-css-tree-patch-json",
}
```

**Comment by romansp** [comment]
In my case adding `'node_modules/css-tree/data/patch.json'` to `traceInclude` wasn't enough and also had include `mdn-data` files.

```json
{
    "error": {
        "message": "[500] [IPX_ERROR] Cannot find module 'mdn-data/css/at-rules.json'\nRequire stack:\n- /app/server/node_modules/css-tree/lib/data.js"
    }
}
```

nuxt.config.ts
```js
nitro: {
  externals: {
    traceInclude: [
      "node_modules/css-tree/data/patch.json",
      "node_modules/mdn-data/css/at-rules.json",
      "node_modules/mdn-data/css/properties.json",
      "node_modules/mdn-data/css/syntaxes.json",
    ],
  },
},
```

**Comment by qlash** [comment]
Can we add to the options something like IgnorePattern (regex) that would skip IPX for a given pattern and, for example, return the URL without _ipx in that case?

**Comment by IqroNegoro** [comment]
any update?

**Comment by Kuuzoo** [comment]
> any update?

I'm a bit uncertain why, but I happen to have had no issues after refreshing my lockfile some days ago.
Maybe it has been resolved in the dependencies? Maybe give refreshing the lockfile a shot and see if that works for you too

**Comment by IqroNegoro** [comment]
> > any update?
> 
> I'm a bit uncertain why, but I happen to have had no issues after refreshing my lockfile some days ago. Maybe it has been resolved in the dependencies? Maybe give refreshing the lockfile a shot and see if that works for you too

for svg i just convert to png lol,  i just pushing too many commit and it didnt fix at all.

oh are you feeling that image is flickering / blinking when it visible to viewport? the ipx just refetch every it come to viewport, not cache it... i wonder why

**Comment by capraruioan** [comment]
did anyone manage to fix this? nothing from this issue works for me

**Comment by bakedPotatoLord** [comment]
I'm still having this issue. any updates on merging?

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/image/pull/2094
