### ISSUE TITLE
How to fix NuxtImage not loaded in production

### ISSUE THREAD

**Issue by vanminhquangtri** [nuxt/image#960]
Hello,

My app is:
- "nuxt": "^3.6.5",
- "@nuxt/image": "^1.0.0-rc.1",
- build command: nuxt build
- ssr: true
- My website is deployed in AWS.

My images is located at folder: src/public/images. The provider is IPX.
Image is loaded perfect on localhost. But in production, image is not loaded without any error thrown. 

What is tried is:
- Change to @nuxt/image-edge: not work
- Create folder public at the root, then create folder images inside folder public then put all image inside this folder images: still not work
- Deploy on netlify instead of AWS: not work, same error happens.

If I use the external image url, it works perfect.
So what I guess is, the deployment if NuxtImage somehow not able to render image. It just render the url. 

I would love to receive any advice to solve this problem. Thank you.

**Comment by vanminhquangtri** [comment]
Hello brothers, can anyone who already have the same problem, can you please share your solution to me because I think I already tried every solution.

**Comment by vanminhquangtri** [comment]
@danielroe I will make a demo, thank

**Comment by vanminhquangtri** [comment]
@danielroe I have deployed my code to this link:
https://uagzjc4knsohwzu26dgg3btsqi0gtjul.lambda-url.ap-southeast-1.on.aws/1000/live

I you see all the png image are not rendered, while svg is rendered ok.
![image](https://github.com/nuxt/image/assets/70369658/28b75b6d-49e6-46ce-955c-4b1946d3cd32)

The image url format is: 
```
https://uagzjc4knsohwzu26dgg3btsqi0gtjul.lambda-url.ap-southeast-1.on.aws/_ipx/_/images/content.png
```

In my component I use NuxtImage as normal basic:
```
<NuxtImg src="/images/content.png" class="mx-auto" />
```

Due to sensitive I can't share the code, but I can share the nuxt.config.ts as below:

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  app: {
    buildAssetsDir: '/assets/',
    head: {
      htmlAttrs: { lang: 'ja' },
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'robots', content: 'noindex, noarchive, nofollow' },
      ],
    },
  },
  devtools: { enabled: false },
  experimental: {
    componentIslands: true,
  },
  imports: { dirs: ['stores'] },
  modules: [
    '@nuxt/image',
    '@nuxtjs/tailwindcss',
    '@pinia/nuxt',
    'nuxt-headlessui',
    'nuxt-icon',
    '@pinia/nuxt',
    'nuxt-vitest',
  ],
  nitro: {
    preset: 'aws-lambda',
    serveStatic: true,
  },
  ssr: true,
  srcDir: 'src',
  telemetry: false,
  typescript: {
    typeCheck: true,
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {
        overrideBrowserslist: ['> 1%', 'last 2 versions', 'not dead', 'not ie 11'],
      },
    },
  },
  headlessui: { prefix: 'H' },
  icon: { aliases: undefined, class: undefined, size: undefined },
  image: {
    domains: ['pravatar.cc'],
    alias: {
      pravatar: 'https://i.pravatar.cc/',
    },
  },
  tailwindcss: {
    viewer: false,
  },
});

```

And this is my package.json file, I don't have any special config for image:
```
{
  "name": "nuxt-app",
  "private": true,
  "engines": {
    "node": "18.x"
  },
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "test": "npm run lint",
    "test:unit": "NODE_ENV=test vitest run",
    "test:duplicates": "jscpd",
    "lint": "npm run lint:js && npm run lint:prettier",
    "lint:js": "eslint --ext \".ts,.vue\" --ignore-path .gitignore .",
    "lint:prettier": "prettier --check .",
    "lint:fix": "prettier --write --list-different . && npm run lint:js --fix"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/image": "^1.0.0-rc.1",
    "@nuxt/types": "^2.17.1",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/google-fonts": "^3.0.2",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@tailwindcss/forms": "^0.5.4",
    "@types/node": "^18.17.8",
    "@typescript-eslint/parser": "^5.62.0",
    "@vitejs/plugin-vue": "^4.3.1",
    "@vitest/coverage-istanbul": "^0.30.1",
    "@vue/test-utils": "^2.4.1",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.46.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-vue-scoped-css": "^2.5.0",
    "happy-dom": "^10.10.4",
    "jscpd": "^3.5.9",
    "mitt": "^3.0.1",
    "nuxt": "^3.6.5",
    "nuxt-headlessui": "^1.1.4",
    "nuxt-icon": "^0.5.0",
    "nuxt-vitest": "^0.7.2",
    "postcss": "^8.4.27",
    "prettier": "^3.0.1",
    "prettier-plugin-tailwindcss": "^0.5.2",
    "sass": "^1.65.1",
    "serverless": "^3.34.0",
    "serverless-prune-plugin": "^2.0.2",
    "sharp": "^0.32.5",
    "typescript": "^5.1.6",
    "vitest": "^0.30.1",
    "vitest-environment-nuxt": "^0.10.2",
    "vue-tsc": "^1.8.8"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.6"
  },
  "overrides": {
    "vue": "latest"
  }
}
```

**Comment by nyxx47** [comment]
Yeah this is issues was founded along time ago but still the same, it's not work well on production.

**Comment by vanminhquangtri** [comment]
@nyxx47 thank you. I decide not to use NuxtImage, I will use the img tag instead.

**Comment by MarkDonatelli** [comment]
> Yeah this is issues was founded along time ago but still the same, it's not work well on production.

2/26/2024

I continue to encounter problems with NuxtImg in production settings. While some images display correctly, others randomly fail to do so. This inconsistency has led me back to standard img tags

**Comment by matrixmandeep** [comment]
same issue with me even I'm not using the nuxtImage

**Comment by JuBertoo** [comment]
I am encountering the same issue in production. Is there a solution available to date ? 
I regret having to stop using nuxtImage in my project.

**Comment by jrusi** [comment]
For me adding this line did the trick:
image: {
    provider: "ipx",
  },

in nuxt.config.ts

**Comment by JuBertoo** [comment]
Thank you @jrusi,  but it's still not working. 
Here's my nuxt.config configuration for nuxtImage, everything seems correct  : 

image: {
    provider: 'netlify',
    netlify: {
      baseURL: 'https://xxxxxxx.netlify.app/',
    },
    domains: ['xxxxxxxx.netlify.app', 'xxxxxxxxxx.supabase.co'],
    supplier: 'ipx',
    quality: 80,
    screens: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      xxl: 1536,
      '2xl': 1536,
    },
  },

**Comment by jrusi** [comment]
Did you try with:
provider: ‘ipx’
Instead of 
provider: ‘netlify’
?

**Comment by JuBertoo** [comment]
Yes, I did the test with only provider: ‘ipx’ but I still get the same 404 error:
GET https://xxxxxxxx.netlify.app/.netlify/images?w=512&q=80&url=%2Fimages%2Ftypes%2Feducation.webp

**Comment by abogawat** [comment]
I can confirm that using `provider: 'ipx'` solves the issue.

**Comment by solomonade1** [comment]
@abogawat  with the provider set. it not showing in production

  image: {
    dir: "assets/img",
    provider: "ipx",
  },

**Comment by abogawat** [comment]
> @abogawat with the provider set. it not showing in production
> 
> image: { dir: "assets/img", provider: "ipx", },

Sorry @solomonade1, not sure what you mean. Could it be that the value for `dir` is wrong? I didn't have to set it in my case. Just the `provider` value worked.

**Comment by alivadjid** [comment]
I have the same issue. 

In network browser tab on getting images this error:

`[500] [IPX_ERROR] \nSomething went wrong installing the \"sharp\" module\n\nCannot find module '../build/Release/sharp-linux-x64.node'\nRequire stack:\n-`

This is a problem from sharp dep in NuxtImage.

Here is discussion about this and variants to solve: https://github.com/nuxt/image/issues/1210

**Comment by codehunger-team** [comment]
I am also facing the same issue, I believe nuxt is still under development, please fix the IPX problem, or nuxtIMage module issue, in the local it's working perfectly fine, but on the live, it doesn't work,

**Comment by Necrelox** [comment]
Hey, why is the issue closed when the problem still exists?

**Comment by danielroe** [comment]
@Necrelox if you are encountering an issue, please open a new issue with a reproduction (none was ever provided here).

**Comment by Necrelox** [comment]
@danielroe it's an error on my part, due to an incomprehension, I tried to use nuxt image in SPA 🤡 i'm sorry.

**Comment by westwards** [comment]
I have the same issue.
Here is my solution, hope it helps you.

[My development environment]
mac os m1 chip
"@nuxt/image": "1.8.1",
"nuxt": "^3.14.1592",
ssr: true


I found that the key to the problem is that **the local development environment is different from the server environment, and the files required by the server are missing.**
I tried various methods but couldn't solve it, so I used the dumbest way.
Anyway, it works now!

1. Put the files in any directory on the server and then enter, run  'npm install' and 'npm run build'

2. After build, you will get the .output folder. Download the files below
.output/server/node_modules/sharp/build/Release/sharp-linux-x64.node
.output/server/node_modules/sharp/vendor/8.14.5/linux-x64

3. Put them to your local .output folder.


PS: As I build in local, the following sharp files are generated ( which CANNOT BE USED FOR linux)
build/Release/sharp-darwin-arm64v8.node
vendor/8.14.5/darwin-arm64v8

Hope there is a smarter solution.

**Comment by chstappert** [comment]
I run into this issue as well and it was not fun. I solved like this at `package.json`

`{
  "pnpm": {
    "overrides": {
      "sharp": "0.33.5"
    }
  }
}`

**Comment by tgmkubi** [comment]
On the local development NuxtImg was running smoothly, but after deployment I could not see the NuxtImg images. If you're using @nuxt/ui, please remove the below modules according to the official @nuxt/ui [documentation.](https://ui.nuxt.com/getting-started/installation#modules)

Nuxt UI will automatically install the @nuxt/icon, @nuxtjs/tailwindcss and @nuxtjs/color-mode modules for you.
You should remove them from your modules and dependencies if you've previously installed them.

For your guidance, please check below code;
packages/frontend/nuxt.config.ts

**Comment by Micenjia** [comment]
I used a Netlify deployment and couldn't show up with `<NuxtImg/>` ,
Which was solved in this way
1.  Replacing `<NuxtImg />`  with `<NuxtPicture />`  
2.  Adding `provider: 'netlify'`

**Comment by Emili-HD** [comment]
If you’re using a Mac or Windows environment and you deploy the app in a Linux environment, Sharp doesn’t work properly (it behaves differently on each operating system).
To make it work correctly, I’ve created a sharp.sh file in the root of the site.

`
#!/bin/bash
SERVER_DIR="$(dirname "$0")/server"

cd "$SERVER_DIR" || {
  echo "No se pudo acceder a la carpeta $SERVER_DIR"
  exit 1
}

echo "Eliminando node_modules previos..."
rm -rf node_modules package-lock.json

if [ ! -f package.json ]; then
  echo "{}" > package.json
fi

echo "Instalando sharp para Linux..."
npm install sharp --platform=linux --arch=x64 --force

echo "Verificando instalación de sharp..."
node -e "require('sharp') && console.log('Sharp está funcionando correctamente.')"

echo "Sharp instalado y listo para IPX en producción."
`

When you deploy, run ./sharp.sh and the correct version of Sharp will be installed. This should make it work properly. ;)

**Comment by Mou7s** [comment]
I had the same problem, this is how I solved it:
`pnpm i -D sharp`
`pnpm approve-builds`
