### ISSUE TITLE
404 not found when deployed to firebase hosting

### ISSUE THREAD

**Issue by crunchwrap89** [nuxt/image#994]
I am using nuxt 3.7.1 and nuxt/image 1.0.0-rc.1

When running my app locally below works fine:

```js
          <NuxtImg
            width="550"
            class="w-[550px]"
            src="/img/GeoQuestrLogov2.png"
            alt="geoquestr-logo"
            :placeholder="[50, 25, 75, 5]"
          />
```

but when built and deployed to firebase hosting i get error:

```GET https://geoquestr.com/_ipx/q_75&s_50x25/img/GeoQuestrLogov2.png 404 ```
```IPX Error: Error: File not found (/public/img/GeoQuestrLogov2.png)```

The application is deployed as a cloud function.

Any ideas why this doesnt work?

**Comment by hi-reeve** [comment]
also happen deploying on vercel

**Comment by ziadsarour** [comment]
I've fixed this issue by not completely following the [Nitro tutorial with the Firebase preset](https://nitro.unjs.io/deploy/providers/firebase).

I've changed my ```firebase.json``` file to this :
```
"functions": {
    "runtime": "nodejs20",
    "source": ".output"
  }
```

The source is now ```.output``` and not ```.output/server``` anymore because the ```public``` folder should be uploaded to Firebase Functions, otherwise files could not be loaded by IPX fs.

Finally, I have a script to deploy the website :
```
jq '.main |= "server/index.mjs"' .output/server/package.json > .output/package.json
rm -f .output/server/package.json
mv .output/server/node_modules .output/.

firebase deploy --only hosting
firebase deploy --only functions:server
```

For the Firebase Functions to work when ```index.mjs``` is not in the root folder, we have to move ```node_modules``` and ```package.json``` to the root folder (ie : ```.output```) and modify the "main" value of the ```package.json``` with the new ```index.mjs``` path (ie : ```server/index.mjs```.

(jq is a command to manipulate JSON using CLI, you need to install it or modify ```package.json``` using your own method)

We then have this folder structure :
```
.output
|-- public
    |-- images
        |-- logo.png
        |-- ...
|-- server
    |-- index.mjs
    |-- ...
|-- package.json
|-- node_modules
```

**Comment by crunchwrap89** [comment]
> I've fixed this issue by not completely following the [Nitro tutorial with the Firebase preset](https://nitro.unjs.io/deploy/providers/firebase).
> 
> I've changed my `firebase.json` file to this :
> 
> ```
> "functions": {
>     "runtime": "nodejs20",
>     "source": ".output"
>   }
> ```
> 
> The source is now `.output` and not `.output/server` anymore because the `public` folder should be uploaded to Firebase Functions, otherwise files could not be loaded by IPX fs.
> 
> Finally, I have a script to deploy the website :
> 
> ```
> jq '.main |= "server/index.mjs"' .output/server/package.json > .output/package.json
> rm -f .output/server/package.json
> mv .output/server/node_modules .output/.
> 
> firebase deploy --only hosting
> firebase deploy --only functions:server
> ```
> 
> For the Firebase Functions to work when `index.mjs` is not in the root folder, we have to move `node_modules` and `package.json` to the root folder (ie : `.output`) and modify the "main" value of the `package.json` with the new `index.mjs` path (ie : `server/index.mjs`.
> 
> (jq is a command to manipulate JSON using CLI, you need to install it or modify `package.json` using your own method)
> 
> We then have this folder structure :
> 
> ```
> .output
> |-- public
>     |-- images
>         |-- logo.png
>         |-- ...
> |-- server
>     |-- index.mjs
>     |-- ...
> |-- package.json
> |-- node_modules
> ```

This does not work for me.

**Comment by crunchwrap89** [comment]
I can confirm that this issue still persists in Nuxt 3.8 with Nuxt/Img 1.0

**Comment by desk-pro** [comment]
Same problem here. I'm using Node 18

**Comment by fahmifitu** [comment]
> > I've fixed this issue by not completely following the [Nitro tutorial with the Firebase preset](https://nitro.unjs.io/deploy/providers/firebase).
> > I've changed my `firebase.json` file to this :
> > ```
> > "functions": {
> >     "runtime": "nodejs20",
> >     "source": ".output"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The source is now `.output` and not `.output/server` anymore because the `public` folder should be uploaded to Firebase Functions, otherwise files could not be loaded by IPX fs.
> > Finally, I have a script to deploy the website :
> > ```
> > jq '.main |= "server/index.mjs"' .output/server/package.json > .output/package.json
> > rm -f .output/server/package.json
> > mv .output/server/node_modules .output/.
> > 
> > firebase deploy --only hosting
> > firebase deploy --only functions:server
> > ```
> > 
> > 
> >     
> >   
> > For the Firebase Functions to work when `index.mjs` is not in the root folder, we have to move `node_modules` and `package.json` to the root folder (ie : `.output`) and modify the "main" value of the `package.json` with the new `index.mjs` path (ie : `server/index.mjs`.
> > (jq is a command to manipulate JSON using CLI, you need to install it or modify `package.json` using your own method)
> > We then have this folder structure :
> > ```
> > .output
> > |-- public
> >     |-- images
> >         |-- logo.png
> >         |-- ...
> > |-- server
> >     |-- index.mjs
> >     |-- ...
> > |-- package.json
> > |-- node_modules
> > ```
> 
> This does not work for me. If i try exactly according to this instruction i get below error message:
> 
> ```
> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parse.js' is not defined by "exports" in
> ```

Thank you sir. this fixed the issue!

**Comment by Baroshem** [comment]
Closing as the solution was provided and the issue seems to be fixed from the comment above.
